### ISSUE TITLE
"Action not found" when pressing enter in form

### ISSUE THREAD

**Issue by namednil** [FlorianPusse/Lingoturk#1]
Pressing enter in a form can cause an error stating "Action not Found", for instance when you enter the worker ID.
Would also be nice if pressing enter could lead to the next question in other cases instead of just doing nothing.

**Comment by FlorianPusse** [comment]
This bug has been fixed with commit 0c208eb21825e9d948e6dcbb9a15d40dfac74f07. I agree with your idea to continue to the next question by pressing enter. I created a feature request here: #3
