### ISSUE TITLE
Unable to generate ApplicationSecret ./sbt: line 3: ./sbt-dist/bin/sbt: Permission denied

### ISSUE THREAD

**Issue by izaskr** [FlorianPusse/Lingoturk#13]
When running `./sbt playGenerateSecret`, I get an error `./sbt: line 3: ./sbt-dist/bin/sbt: Permission denied`.

I use Ubuntu 16.04, Java SE Development Kit 8 for Linux x64, the version of PostgreSQL is 9.5+173.

**Comment by dmhowcroft** [comment]
Hm, it's been years since I tried to install this, so I don't remember what you need to do, but maybe you need to run it as `root` or with `sudo`? That is:

    sudo ./sbt playGenerateSecret

That is just a guess, though; I'll add a better comment if I find some time to look into it.

**Comment by dmhowcroft** [comment]
Apparently `sbt` and `sbt-dist/bin/sbt` are not set to be executable by default. Just run

    chmod u+x sbt sbt-dist/bin/sbt

from your `Lingoturk/lingoturk/` directory and it should work

**Comment by dmhowcroft** [comment]
Just pushed an update to the repo with this fix.

**Comment by izaskr** [comment]
Thanks! I made `sbt` executable, but not `sbt-dist/bin/sbt`, that's why it didn't work earlier.
